name: Run scratchattach script

on:
  workflow_dispatch:
    inputs:
      py_version:
        description: "Python Version"
        required: true
        type: choice
        options:
          - "3.8"
          - "3.10"
          - "3.10.3"
          - "3.11"
          - "3.11.3"
          - "3.12"
          - "3.12.4"
          - "3.12.5"
        default: "3.11.3"
      pip:
        description: "Update pip?"
        type: boolean
        required: true
        default: true
      run:
        description: "Run scratch_chat.py?"
        type: boolean
        required: true
        default: false
  schedule:
    - cron: "*/360 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        script: ["message_viewer.py", "scratch_chat.py"]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '${{ inputs.py_version || "3.11.3"}}' # install the python version needed
          
      - name: install scratchattach
        run: |
          pip install -U scratchattach

      - name: update pip
        if: "${{ inputs.pip || true}}"
        run: |
          python3 -m pip install --upgrade pip
          
      - name: execute all py scripts # run message_viewer.py
        if: "${{ inputs.run || false}}"
        run: |
          python3 ${{ matrix.script }}

      - name: execute message viewer only
        if: "${{ !inputs.run }} && strategy.job_index === 0"
        run: |
          python3 message_viewer.py
