name: Monthly Branch Merge

on:
  schedule:
    # Run at 00:00 UTC on the first day of every month
    - cron: '0 0 1 * *'

  workflow_dispatch:

jobs:
  create_and_merge_pr1:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge
        run: |
          git checkout main 
          git pull origin main
          git merge scratch_chat_dev
          git push -u origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create_and_merge_pr2:
    needs: create_and_merge_pr1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge
        run: |
          git checkout scratch_chat_dev 
          git pull origin scratch_chat_deb
          git merge main
          git push -u origin scratch_chat_dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
