name: Run scratchattach script

on:
  workflow_dispatch:
    inputs:
      py_version:
        description: "Python Version"
        required: true
        type: choice
        options:
          - "3.8"
          - "3.10"
          - "3.10.3"
          - "3.11"
          - "3.11.3"
          - "3.12"
          - "3.12.4"
          - "3.12.5"
        default: "3.11.3"
      runner:
        description: "Run on which OS?"
        type: choice
        required: true
        options:
          - "macos"
          - "ubuntu"
          - "windows"
        default: "ubuntu"
      pip:
        description: "Update pip?"
        type: boolean
        required: true
        default: true
      run:
        description: "Run which file?"
        type: choice
        required: true
        options:
          - "message_viewer.py"
          - "scratch_chat.py"
        default: "message_viewer.py"
  schedule:
    - cron: "00 00,06,12,18 * * *"

jobs:
  run1:
    runs-on: "${{ github.events.inputs.runner == '' && 'ubuntu' || github.events.inputs.runner }}-latest"
    continue-on-error: true
    strategy:
      fail-fast: false
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4.1.7 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: "${{ github.events.inputs.py_version == '' && github.events.inputs.py_versions || '3.11.3' }}" # install the python version needed
          
      - name: install scratchattach
        run: |
          pip install -U scratchattach

      - name: update pip
        if: "${{ github.events.inputs.pip == '' && true || github.events.inputs.py_version }}"
        run: |
          python3 -m pip install --upgrade pip

      - name: execute ${{ github.events.inputs.run == '' && 'message_viewer.py' || github.events.inputs.run }}
        run: |
          python3 ${{ github.events.inputs.run == '' && 'message_viewer.py' || github.events.inputs.run }}

      - uses: actions/cache/save@v4.0.2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - uses: actions/cache/save@v4.0.2
        if: startsWith(runner.os, 'macOS')
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - uses: actions/cache/save@v4.0.2
        if: startsWith(runner.os, 'Windows')
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
